module.exports = [
  {
    value: "2YG-00323",
    Description:
      "WinSmllBusSvrPremAddCALSt 2011 64Bit English 1Pk DSP OEI 1 Clt Dvc CAL",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Small Bus Svr PremAddOn CAL Ste",
    "Start Effective Date": "01/01/2011",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "01/01/2011"
  },
  {
    value: "2YG-00324",
    Description:
      "WinSmllBusSvrPremAddCALSt 2011 64Bit French 1pk DSP OEI 1 Clt Device CAL",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Small Bus Svr PremAddOn CAL Ste",
    "Start Effective Date": "01/01/2011",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "01/01/2011"
  },
  {
    value: "2YG-00342",
    Description:
      "WinSmllBusSvrPremAddCALSt 2011 64Bit English 1Pk DSP OEI 5 Clt Dvc CAL",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Small Bus Svr PremAddOn CAL Ste",
    "Start Effective Date": "01/01/2011",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "01/01/2011"
  },
  {
    value: "2YG-00343",
    Description:
      "WinSmllBusSvrPremAddCALSt 2011 64Bit French 1pk DSP OEI 5 Clt Device CAL",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Small Bus Svr PremAddOn CAL Ste",
    "Start Effective Date": "01/01/2011",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "01/01/2011"
  },
  {
    value: "2YG-00361",
    Description:
      "WinSmllBusSvrPremAddCALSt 2011 64Bit English 1pk DSP OEI 1 Clt User CAL",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Small Bus Svr PremAddOn CAL Ste",
    "Start Effective Date": "01/01/2011",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "01/01/2011"
  },
  {
    value: "2YG-00362",
    Description:
      "WinSmllBusSvrPremAddCALSt 2011 64Bit French 1pk DSP OEI 1 Clt User CAL",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Small Bus Svr PremAddOn CAL Ste",
    "Start Effective Date": "01/01/2011",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "01/01/2011"
  },
  {
    value: "2YG-00380",
    Description:
      "WinSmllBusSvrPremAddCALSt 2011 64Bit English 1pk DSP OEI 5 Clt User CAL",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Small Bus Svr PremAddOn CAL Ste",
    "Start Effective Date": "01/01/2011",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "01/01/2011"
  },
  {
    value: "2YG-00381",
    Description:
      "WinSmllBusSvrPremAddCALSt 2011 64Bit French 1pk DSP OEI 5 Clt User CAL",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Small Bus Svr PremAddOn CAL Ste",
    "Start Effective Date": "01/01/2011",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "01/01/2011"
  },
  {
    value: "43R-00007",
    Description: "Win Pro GGK N 8 Win32 English 1pk DSP ORT OEI EEA Only DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro GGK N",
    "Start Effective Date": "10/01/2012",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "10/01/2012"
  },
  {
    value: "43R-00010",
    Description: "Win Pro GGK N 8 Win32 French 1pk DSP ORT OEI EEA Only DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro GGK N",
    "Start Effective Date": "10/01/2012",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "10/01/2012"
  },
  {
    value: "43R-00031",
    Description: "Win Pro GGK N 8 64Bit English 1pk DSP ORT OEI EEA Only DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro GGK N",
    "Start Effective Date": "10/01/2012",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "10/01/2012"
  },
  {
    value: "43R-00034",
    Description: "Win Pro GGK N 8 64Bit French 1pk DSP ORT OEI EEA Only DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro GGK N",
    "Start Effective Date": "10/01/2012",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "10/01/2012"
  },
  {
    value: "44R-00012",
    Description: "Win GGK 8 Win32 English 1pk DSP ORT OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win GGK",
    "Start Effective Date": "10/01/2012",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "10/01/2012"
  },
  {
    value: "44R-00015",
    Description: "Win GGK 8 Win32 French 1pk DSP ORT OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win GGK",
    "Start Effective Date": "10/01/2012",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "10/01/2012"
  },
  {
    value: "44R-00048",
    Description: "Win GGK 8 64Bit English 1pk DSP ORT OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win GGK",
    "Start Effective Date": "10/01/2012",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "10/01/2012"
  },
  {
    value: "44R-00051",
    Description: "Win GGK 8 64Bit French 1pk DSP ORT OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win GGK",
    "Start Effective Date": "10/01/2012",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "10/01/2012"
  },
  {
    value: "44R-00175",
    Description: "Win GGK 8.1 x64 French 1pk DSP ORT OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win GGK",
    "Start Effective Date": "09/01/2013",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "09/01/2013"
  },
  {
    value: "44R-00184",
    Description: "Win GGK 8.1 x64 English 1pk DSP ORT OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win GGK",
    "Start Effective Date": "09/01/2013",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "09/01/2013"
  },
  {
    value: "44R-00215",
    Description: "Win GGK 8.1 x32 French 1pk DSP ORT OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win GGK",
    "Start Effective Date": "09/01/2013",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "09/01/2013"
  },
  {
    value: "44R-00224",
    Description: "Win GGK 8.1 x32 English 1pk DSP ORT OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win GGK",
    "Start Effective Date": "09/01/2013",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "09/01/2013"
  },
  {
    value: "47R-00007",
    Description: "Win GGK N 8 Win32 English 1pk DSP ORT OEI EEA Only DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win GGK N",
    "Start Effective Date": "10/01/2012",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "10/01/2012"
  },
  {
    value: "47R-00010",
    Description: "Win GGK N 8 Win32 French 1pk DSP ORT OEI EEA Only DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win GGK N",
    "Start Effective Date": "10/01/2012",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "10/01/2012"
  },
  {
    value: "47R-00031",
    Description: "Win GGK N 8 64Bit English 1pk DSP ORT OEI EEA Only DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win GGK N",
    "Start Effective Date": "10/01/2012",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "10/01/2012"
  },
  {
    value: "47R-00034",
    Description: "Win GGK N 8 64Bit French 1pk DSP ORT OEI EEA Only DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win GGK N",
    "Start Effective Date": "10/01/2012",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "10/01/2012"
  },
  {
    value: "4YR-00012",
    Description: "Win Pro GGK 8 Win32 English 1pk DSP ORT OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro GGK",
    "Start Effective Date": "10/01/2012",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "10/01/2012"
  },
  {
    value: "4YR-00015",
    Description: "Win Pro GGK 8 Win32 French 1pk DSP ORT OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro GGK",
    "Start Effective Date": "10/01/2012",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "10/01/2012"
  },
  {
    value: "4YR-00048",
    Description: "Win Pro GGK 8 64Bit English 1pk DSP ORT OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro GGK",
    "Start Effective Date": "10/01/2012",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "10/01/2012"
  },
  {
    value: "4YR-00051",
    Description: "Win Pro GGK 8 64Bit French 1pk DSP ORT OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro GGK",
    "Start Effective Date": "10/01/2012",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "10/01/2012"
  },
  {
    value: "4YR-00173",
    Description: "Win Pro GGK 8.1 x64 French 1pk DSP ORT OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro GGK",
    "Start Effective Date": "09/01/2013",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "09/01/2013"
  },
  {
    value: "4YR-00182",
    Description: "Win Pro GGK 8.1 x64 English 1pk DSP ORT OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro GGK",
    "Start Effective Date": "09/01/2013",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "09/01/2013"
  },
  {
    value: "4YR-00210",
    Description: "Win Pro GGK 8.1 x32 English 1pk DSP ORT OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro GGK",
    "Start Effective Date": "09/01/2013",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "09/01/2013"
  },
  {
    value: "4YR-00213",
    Description: "Win Pro GGK 8.1 x32 French 1pk DSP ORT OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro GGK",
    "Start Effective Date": "09/01/2013",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "09/01/2013"
  },
  {
    value: "4YR-00248",
    Description: "Win Pro GGK 10 64Bit French 1pk DSP ORT OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro GGK",
    "Start Effective Date": "07/01/2015",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "07/01/2015"
  },
  {
    value: "4YR-00258",
    Description: "Win Pro GGK 10 64Bit English 1pk DSP ORT OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro GGK",
    "Start Effective Date": "07/01/2015",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "07/01/2015"
  },
  {
    value: "4YR-00287",
    Description: "Win Pro GGK 10 Win32 English 1pk DSP ORT OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro GGK",
    "Start Effective Date": "07/01/2015",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "07/01/2015"
  },
  {
    value: "4YR-00290",
    Description: "Win Pro GGK 10 Win32 French 1pk DSP ORT OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro GGK",
    "Start Effective Date": "07/01/2015",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "07/01/2015"
  },
  {
    value: "6PC-00020",
    Description:
      "GGK-Win Pro 7 SP1 32-bit/64-bit English Legalization DSP OEI 611 DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "GGK - Win Pro",
    "Start Effective Date": "03/01/2011",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "03/01/2011"
  },
  {
    value: "6UA-03542",
    Description:
      "Win Small Bus CAL Ste 2011 64Bit English 1pk DSP OEI 1 Clt Device CAL",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Small Bus CAL Ste",
    "Start Effective Date": "01/01/2011",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "01/01/2011"
  },
  {
    value: "6UA-03543",
    Description:
      "Win Small Bus CAL Ste 2011 64Bit French 1pk DSP OEI 1 Clt Device CAL",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Small Bus CAL Ste",
    "Start Effective Date": "01/01/2011",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "01/01/2011"
  },
  {
    value: "6UA-03561",
    Description:
      "Win Small Bus CAL Ste 2011 64Bit English 1pk DSP OEI 5 Clt Device CAL",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Small Bus CAL Ste",
    "Start Effective Date": "01/01/2011",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "01/01/2011"
  },
  {
    value: "6UA-03562",
    Description:
      "Win Small Bus CAL Ste 2011 64Bit French 1pk DSP OEI 5 Clt Device CAL",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Small Bus CAL Ste",
    "Start Effective Date": "01/01/2011",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "01/01/2011"
  },
  {
    value: "6UA-03580",
    Description:
      "Win Small Bus CAL Ste 2011 64Bit English 1pk DSP OEI 1 Clt User CAL",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Small Bus CAL Ste",
    "Start Effective Date": "01/01/2011",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "01/01/2011"
  },
  {
    value: "6UA-03581",
    Description:
      "Win Small Bus CAL Ste 2011 64Bit French 1pk DSP OEI 1 Clt User CAL",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Small Bus CAL Ste",
    "Start Effective Date": "01/01/2011",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "01/01/2011"
  },
  {
    value: "6UA-03599",
    Description:
      "Win Small Bus CAL Ste 2011 64Bit English 1pk DSP OEI 5 Clt User CAL",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Small Bus CAL Ste",
    "Start Effective Date": "01/01/2011",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "01/01/2011"
  },
  {
    value: "6UA-03600",
    Description:
      "Win Small Bus CAL Ste 2011 64Bit French 1pk DSP OEI 5 Clt User CAL",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Small Bus CAL Ste",
    "Start Effective Date": "01/01/2011",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "01/01/2011"
  },
  {
    value: "FQC-06941",
    Description: "Win Pro 8.1 x64 French 1pk DSP OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro",
    "Start Effective Date": "09/01/2013",
    "End Effective Date": "11/01/2016",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "10/31/2016",
    Language: "French",
    "Add Date": "09/01/2013"
  },
  {
    value: "FQC-06950",
    Description: "Win Pro 8.1 x64 English 1pk DSP OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro",
    "Start Effective Date": "09/01/2013",
    "End Effective Date": "11/01/2016",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "10/31/2016",
    Language: "English",
    "Add Date": "09/01/2013"
  },
  {
    value: "FQC-06979",
    Description: "Win Pro 8.1 x32 French 1pk DSP OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro",
    "Start Effective Date": "09/01/2013",
    "End Effective Date": "11/01/2016",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "10/31/2016",
    Language: "French",
    "Add Date": "09/01/2013"
  },
  {
    value: "FQC-06988",
    Description: "Win Pro 8.1 x32 English 1pk DSP OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro",
    "Start Effective Date": "09/01/2013",
    "End Effective Date": "11/01/2016",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "10/31/2016",
    Language: "English",
    "Add Date": "09/01/2013"
  },
  {
    value: "FQC-08111",
    Description:
      "Win Pro 8.1 32-bit/x64 French 1pk DSP OEI Not to China Medialess",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro",
    "Start Effective Date": "12/01/2013",
    "End Effective Date": "11/01/2016",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "10/31/2016",
    Language: "French",
    "Add Date": "12/01/2013"
  },
  {
    value: "FQC-08115",
    Description:
      "Win Pro 8.1 32-bit/x64 English 1pk DSP OEI Not to China Medialess",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro",
    "Start Effective Date": "12/01/2013",
    "End Effective Date": "11/01/2016",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "10/31/2016",
    Language: "English",
    "Add Date": "12/01/2013"
  },
  {
    value: "FQC-08250",
    Description:
      "Win Pro 7 SP1 32/64 English 1pk DSP OEI Not to China Medialess",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro",
    "Start Effective Date": "12/01/2013",
    "End Effective Date": "11/01/2016",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "10/31/2016",
    Language: "English",
    "Add Date": "12/01/2013"
  },
  {
    value: "FQC-08251",
    Description:
      "Win Pro 7 SP1 32/64 French 1pk DSP OEI Not to China Medialess",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro",
    "Start Effective Date": "12/01/2013",
    "End Effective Date": "11/01/2016",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "10/31/2016",
    Language: "French",
    "Add Date": "12/01/2013"
  },
  {
    value: "FQC-08279",
    Description: "Win Pro 7 SP1 x32 English 1pk DSP OEI Not to China DVD LCP",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro",
    "Start Effective Date": "12/01/2013",
    "End Effective Date": "11/01/2016",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "10/31/2016",
    Language: "English",
    "Add Date": "12/01/2013"
  },
  {
    value: "FQC-08280",
    Description: "Win Pro 7 SP1 x32 French 1pk DSP OEI Not to China DVD LCP",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro",
    "Start Effective Date": "12/01/2013",
    "End Effective Date": "11/01/2016",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "10/31/2016",
    Language: "French",
    "Add Date": "12/01/2013"
  },
  {
    value: "FQC-08289",
    Description: "Win Pro 7 SP1 x64 English 1pk DSP OEI Not to China DVD LCP",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro",
    "Start Effective Date": "12/01/2013",
    "End Effective Date": "11/01/2016",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "10/31/2016",
    Language: "English",
    "Add Date": "12/01/2013"
  },
  {
    value: "FQC-08290",
    Description: "Win Pro 7 SP1 x64 French 1pk DSP OEI Not to China DVD LCP",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro",
    "Start Effective Date": "12/01/2013",
    "End Effective Date": "11/01/2016",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "10/31/2016",
    Language: "French",
    "Add Date": "12/01/2013"
  },
  {
    value: "FQC-08920",
    Description: "Win Pro 10 64Bit French 1pk DSP OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro",
    "Start Effective Date": "07/01/2015",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "07/01/2015"
  },
  {
    value: "FQC-08930",
    Description: "Win Pro 10 64Bit English 1pk DSP OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro",
    "Start Effective Date": "07/01/2015",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "07/01/2015"
  },
  {
    value: "FQC-08960",
    Description: "Win Pro 10 Win32 French 1pk DSP OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro",
    "Start Effective Date": "07/01/2015",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "07/01/2015"
  },
  {
    value: "FQC-08970",
    Description: "Win Pro 10 Win32 English 1pk DSP OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro",
    "Start Effective Date": "07/01/2015",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "07/01/2015"
  },
  {
    value: "G3S-00123",
    Description: "Win Svr Essentials 2012 64Bit English 1pk DSP OEI DVD 1-2CPU",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Essentials",
    "Start Effective Date": "11/01/2012",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "11/01/2012"
  },
  {
    value: "G3S-00124",
    Description: "Win Svr Essentials 2012 64Bit French 1pk DSP OEI DVD 1-2CPU",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Essentials",
    "Start Effective Date": "11/01/2012",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "11/01/2012"
  },
  {
    value: "G3S-00716",
    Description:
      "Win Svr Essentials 2012 R2 x64 English 1pk DSP OEI DVD 1-2CPU",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Essentials",
    "Start Effective Date": "11/01/2013",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "11/01/2013"
  },
  {
    value: "G3S-00717",
    Description: "Win Svr Essentials 2012 R2 x64 French 1pk DSP OEI DVD 1-2CPU",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Essentials",
    "Start Effective Date": "11/01/2013",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "11/01/2013"
  },
  {
    value: "G3S-00842",
    Description:
      "Win Svr Essentials 2012 x64 English 1pk DSP OEI Medialess 1-2CPU",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Essentials",
    "Start Effective Date": "02/01/2015",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "02/01/2015"
  },
  {
    value: "G3S-00843",
    Description:
      "Win Svr Essentials 2012 x64 French 1pk DSP OEI Medialess 1-2CPU",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Essentials",
    "Start Effective Date": "02/01/2015",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "02/01/2015"
  },
  {
    value: "G3S-01045",
    Description: "Win Svr Essentials 2016 64Bit English 1pk DSP OEI DVD 1-2CPU",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Essentials",
    "Start Effective Date": "10/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "10/01/2016"
  },
  {
    value: "G3S-01046",
    Description: "Win Svr Essentials 2016 64Bit French 1pk DSP OEI DVD 1-2CPU",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Essentials",
    "Start Effective Date": "10/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "10/01/2016"
  },
  {
    value: "KW9-00140",
    Description: "Win Home 10 64Bit English 1pk DSP OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "WIN HOME",
    "Start Effective Date": "07/01/2015",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "07/01/2015"
  },
  {
    value: "KW9-00145",
    Description: "Win Home 10 64Bit French 1pk DSP OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "WIN HOME",
    "Start Effective Date": "07/01/2015",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "07/01/2015"
  },
  {
    value: "KW9-00177",
    Description: "Win Home 10 Win32 French 1pk DSP OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "WIN HOME",
    "Start Effective Date": "07/01/2015",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "07/01/2015"
  },
  {
    value: "KW9-00186",
    Description: "Win Home 10 Win32 English 1pk DSP OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "WIN HOME",
    "Start Effective Date": "07/01/2015",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "07/01/2015"
  },
  {
    value: "L3P-00025",
    Description: "WinHome GGK 10 64Bit French 1pk DSP ORT OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Home GGK",
    "Start Effective Date": "07/01/2015",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "07/01/2015"
  },
  {
    value: "L3P-00034",
    Description: "WinHome GGK 10 64Bit English 1pk DSP ORT OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Home GGK",
    "Start Effective Date": "07/01/2015",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "07/01/2015"
  },
  {
    value: "L3P-00067",
    Description: "WinHome GGK 10 Win32 French 1pk DSP ORT OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Home GGK",
    "Start Effective Date": "07/01/2015",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "07/01/2015"
  },
  {
    value: "L3P-00076",
    Description: "WinHome GGK 10 Win32 English 1pk DSP ORT OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Home GGK",
    "Start Effective Date": "07/01/2015",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "07/01/2015"
  },
  {
    value: "P71-06769",
    Description: "Win Svr Datacntr 2012 x64 English 1pk DSP OEI DVD 2 CPU",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Datacenter",
    "Start Effective Date": "11/01/2013",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "09/01/2012"
  },
  {
    value: "P71-06770",
    Description: "Win Svr Datacntr 2012 x64 French 1pk DSP OEI DVD 2 CPU",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Datacenter",
    "Start Effective Date": "11/01/2013",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "09/01/2012"
  },
  {
    value: "P71-06787",
    Description:
      "Win Svr Datacntr 2012 x64 English 1pk DSP OEI 2 CPU Addtl License",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Datacenter",
    "Start Effective Date": "11/01/2013",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "09/01/2012"
  },
  {
    value: "P71-06788",
    Description:
      "Win Svr Datacntr 2012 x64 French 1pk DSP OEI 2 CPU Addtl License",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Datacenter",
    "Start Effective Date": "11/01/2013",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "09/01/2012"
  },
  {
    value: "P71-07714",
    Description:
      "Windows Svr Datacntr 2012 R2 x64 English 1pk DSP OEI DVD 2 CPU",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Datacenter",
    "Start Effective Date": "11/01/2013",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "11/01/2013"
  },
  {
    value: "P71-07715",
    Description:
      "Windows Svr Datacntr 2012 R2 x64 French 1pk DSP OEI DVD 2 CPU",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Datacenter",
    "Start Effective Date": "11/01/2013",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "11/01/2013"
  },
  {
    value: "P71-07785",
    Description:
      "Windows Svr Datacntr 2012 R2 x64 English 1pk DSP OEI DVD 4 CPU",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Datacenter",
    "Start Effective Date": "11/01/2013",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "11/01/2013"
  },
  {
    value: "P71-07786",
    Description:
      "Windows Svr Datacntr 2012 R2 x64 French 1pk DSP OEI DVD 4 CPU",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Datacenter",
    "Start Effective Date": "11/01/2013",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "11/01/2013"
  },
  {
    value: "P71-07984",
    Description: "Win Svr Datacntr 2012 64Bit ENG 1pk DSP OEI Medialess 2 CPU",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Datacenter",
    "Start Effective Date": "12/01/2013",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "12/01/2013"
  },
  {
    value: "P71-07985",
    Description: "Win Svr Datacntr 2012 64Bit FRE 1pk DSP OEI Medialess 2 CPU",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Datacenter",
    "Start Effective Date": "12/01/2013",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "12/01/2013"
  },
  {
    value: "P71-08651",
    Description:
      "Windows Svr Datacntr 2016 64Bit English 1pk DSP OEI DVD 16 Core",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Datacenter",
    "Start Effective Date": "10/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "10/01/2016"
  },
  {
    value: "P71-08652",
    Description:
      "Windows Svr Datacntr 2016 64Bit French 1pk DSP OEI DVD 16 Core",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Datacenter",
    "Start Effective Date": "10/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "10/01/2016"
  },
  {
    value: "P71-08670",
    Description:
      "Windows Svr Datacntr 2016 64Bit English 1pk DSP OEI DVD 24 Core",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Datacenter",
    "Start Effective Date": "10/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "10/01/2016"
  },
  {
    value: "P71-08671",
    Description:
      "Windows Svr Datacntr 2016 64Bit French 1pk DSP OEI DVD 24 Core",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Datacenter",
    "Start Effective Date": "10/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "10/01/2016"
  },
  {
    value: "P71-08691",
    Description:
      "Windows Svr Datacntr 2016 English 1pk DSP OEI 2Cr NoMedia/NoKey AddLic",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Datacenter",
    "Start Effective Date": "10/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "10/01/2016"
  },
  {
    value: "P71-08692",
    Description:
      "Windows Svr Datacntr 2016 French 1pk DSP OEI 2Cr NoMedia/NoKey AddLic",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Datacenter",
    "Start Effective Date": "10/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "10/01/2016"
  },
  {
    value: "P71-08710",
    Description:
      "Windows Svr Datacntr 2016 English 1pk DSP OEI 4Cr NoMedia/NoKey AddLic",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Datacenter",
    "Start Effective Date": "10/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "10/01/2016"
  },
  {
    value: "P71-08711",
    Description:
      "Windows Svr Datacntr 2016 French 1pk DSP OEI 4Cr NoMedia/NoKey AddLic",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Datacenter",
    "Start Effective Date": "10/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "10/01/2016"
  },
  {
    value: "P71-08729",
    Description:
      "Windows Svr Datacntr 2016 English 1pk DSP OEI 16Cr NoMedia/NoKey AddLic",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Datacenter",
    "Start Effective Date": "10/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "10/01/2016"
  },
  {
    value: "P71-08730",
    Description:
      "Windows Svr Datacntr 2016 French 1pk DSP OEI 16Cr NoMedia/NoKey AddLic",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Datacenter",
    "Start Effective Date": "10/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "10/01/2016"
  },
  {
    value: "P73-05328",
    Description: "Win Svr Std 2012 x64 ENG 1pk DSP OEI DVD 2CPU/2VM",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Standard",
    "Start Effective Date": "09/01/2012",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "09/01/2012"
  },
  {
    value: "P73-05329",
    Description: "Win Svr Std 2012 x64 FRE 1pk DSP OEI DVD 2CPU/2VM",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Standard",
    "Start Effective Date": "09/01/2012",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "09/01/2012"
  },
  {
    value: "P73-06165",
    Description: "Windows Svr Std 2012 R2 x64 English 1pk DSP OEI DVD 2CPU/2VM",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Standard",
    "Start Effective Date": "11/01/2013",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "11/01/2013"
  },
  {
    value: "P73-06166",
    Description: "Windows Svr Std 2012 R2 x64 French 1pk DSP OEI DVD 2CPU/2VM",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Standard",
    "Start Effective Date": "11/01/2013",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "11/01/2013"
  },
  {
    value: "P73-06229",
    Description: "Windows Svr Std 2012 R2 x64 English 1pk DSP OEI DVD 4CPU/4VM",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Standard",
    "Start Effective Date": "11/01/2013",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "11/01/2013"
  },
  {
    value: "P73-06230",
    Description: "Windows Svr Std 2012 R2 x64 French 1pk DSP OEI DVD 4CPU/4VM",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Standard",
    "Start Effective Date": "11/01/2013",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "11/01/2013"
  },
  {
    value: "P73-06492",
    Description: "Win Svr Std 2012 64Bit ENG 1pk DSP OEI Medialess 2CPU/2VM",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Standard",
    "Start Effective Date": "12/01/2013",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "12/01/2013"
  },
  {
    value: "P73-06493",
    Description: "Win Svr Std 2012 64Bit FRE 1pk DSP OEI Medialess 2CPU/2VM",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Standard",
    "Start Effective Date": "12/01/2013",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "12/01/2013"
  },
  {
    value: "P73-07113",
    Description: "Windows Svr Std 2016 64Bit English 1pk DSP OEI DVD 16 Core",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Standard",
    "Start Effective Date": "10/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "10/01/2016"
  },
  {
    value: "P73-07114",
    Description: "Windows Svr Std 2016 64Bit French 1pk DSP OEI DVD 16 Core",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Standard",
    "Start Effective Date": "10/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "10/01/2016"
  },
  {
    value: "P73-07132",
    Description: "Windows Svr Std 2016 64Bit English 1pk DSP OEI DVD 24 Core",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Standard",
    "Start Effective Date": "10/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "10/01/2016"
  },
  {
    value: "P73-07133",
    Description: "Windows Svr Std 2016 64Bit French 1pk DSP OEI DVD 24 Core",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Standard",
    "Start Effective Date": "10/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "10/01/2016"
  },
  {
    value: "P73-07153",
    Description:
      "Windows Svr Std 2016 English 1pk DSP OEI 2Cr NoMedia/NoKey (APOS) AddLic",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Standard",
    "Start Effective Date": "10/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "10/01/2016"
  },
  {
    value: "P73-07154",
    Description:
      "Windows Svr Std 2016 French 1pk DSP OEI 2Cr NoMedia/NoKey (APOS) AddLic",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Standard",
    "Start Effective Date": "10/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "10/01/2016"
  },
  {
    value: "P73-07172",
    Description:
      "Windows Svr Std 2016 English 1pk DSP OEI 4Cr NoMedia/NoKey (APOS) AddLic",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Standard",
    "Start Effective Date": "10/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "10/01/2016"
  },
  {
    value: "P73-07173",
    Description:
      "Windows Svr Std 2016 French 1pk DSP OEI 4Cr NoMedia/NoKey (APOS) AddLic",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Standard",
    "Start Effective Date": "10/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "10/01/2016"
  },
  {
    value: "P73-07191",
    Description:
      "Windows Svr Std 2016 English 1pk DSP OEI 16Cr NoMedia/NoKey (APOS)AddLic",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Standard",
    "Start Effective Date": "10/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "10/01/2016"
  },
  {
    value: "P73-07192",
    Description:
      "Windows Svr Std 2016 French 1pk DSP OEI 16Cr NoMedia/NoKey (APOS) AddLic",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Standard",
    "Start Effective Date": "10/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "10/01/2016"
  },
  {
    value: "P73-07213",
    Description:
      "Windows Svr Std 2016 English 1pkDSP OEI 2Cr NoMedia/NoKey(POSOnly)AddLic",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Standard",
    "Start Effective Date": "10/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "10/01/2016"
  },
  {
    value: "P73-07214",
    Description:
      "Windows Svr Std 2016 French 1pkDSP OEI 2Cr NoMedia/NoKey(POSOnly)AddLic",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Standard",
    "Start Effective Date": "10/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "10/01/2016"
  },
  {
    value: "P73-07232",
    Description:
      "Windows Svr Std 2016 English 1pkDSP OEI 4Cr NoMedia/NoKey(POSOnly)AddLic",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Standard",
    "Start Effective Date": "10/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "10/01/2016"
  },
  {
    value: "P73-07233",
    Description:
      "Windows Svr Std 2016 French 1pkDSP OEI 4Cr NoMedia/NoKey(POSOnly)AddLic",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Standard",
    "Start Effective Date": "10/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "10/01/2016"
  },
  {
    value: "P73-07251",
    Description:
      "Windows Svr Std 2016 English 1pkDSP OEI 16CrNoMedia/NoKey(POSOnly)AddLic",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Standard",
    "Start Effective Date": "10/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "10/01/2016"
  },
  {
    value: "P73-07252",
    Description:
      "Windows Svr Std 2016 French 1pkDSP OEI 16Cr NoMedia/NoKey(POSOnly)AddLic",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server Standard",
    "Start Effective Date": "10/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "10/01/2016"
  },
  {
    value: "QLF-00195",
    Description:
      "Win Pro Rfrbishr 7 SP1 32-bit English 3pk DSP 3 OEI 611 DVD RRP Commrcl",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro Refurbisher",
    "Start Effective Date": "09/01/2011",
    "End Effective Date": "11/01/2016",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "10/31/2016",
    Language: "English",
    "Add Date": "09/01/2011"
  },
  {
    value: "QLF-00198",
    Description:
      "Win Pro Rfrbishr 7 SP1 32-bit French 3pk DSP 3 OEI 611 DVD RRP Commrcl",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro Refurbisher",
    "Start Effective Date": "09/01/2011",
    "End Effective Date": "11/01/2016",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "10/31/2016",
    Language: "French",
    "Add Date": "09/01/2011"
  },
  {
    value: "QLF-00311",
    Description: "Win Pro Rfrbishr 7 w/SP1 x64 ENG 3pk DSP 3 OEI RRP Commrcl",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro Refurbisher",
    "Start Effective Date": "07/01/2012",
    "End Effective Date": "11/01/2016",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "10/31/2016",
    Language: "English",
    "Add Date": "07/01/2012"
  },
  {
    value: "QLF-00312",
    Description: "Win Pro Rfrbishr 7 w/SP1 x64 FRE 3pk DSP 3 OEI RRP Commrcl",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro Refurbisher",
    "Start Effective Date": "07/01/2012",
    "End Effective Date": "11/01/2016",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "10/31/2016",
    Language: "French",
    "Add Date": "07/01/2012"
  },
  {
    value: "QLF-00447",
    Description:
      "Win Pro Refurbisher 8.1 32-bit English 3pk DSP 3 OEI DVD RRP Commrcl",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro Refurbisher",
    "Start Effective Date": "08/04/2014",
    "End Effective Date": "11/01/2016",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "10/31/2016",
    Language: "English",
    "Add Date": "08/01/2014"
  },
  {
    value: "QLF-00450",
    Description:
      "Win Pro Refurbisher 8.1 32-bit French 3pk DSP 3 OEI DVD RRP Commrcl",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro Refurbisher",
    "Start Effective Date": "08/04/2014",
    "End Effective Date": "11/01/2016",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "10/31/2016",
    Language: "French",
    "Add Date": "08/01/2014"
  },
  {
    value: "QLF-00473",
    Description:
      "Win Pro Refurbisher 8.1 64-bit English 3pk DSP 3 OEI DVD RRP Commrcl",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro Refurbisher",
    "Start Effective Date": "08/04/2014",
    "End Effective Date": "11/01/2016",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "10/31/2016",
    Language: "English",
    "Add Date": "08/01/2014"
  },
  {
    value: "QLF-00476",
    Description:
      "Win Pro Refurbisher 8.1 64-bit French 3pk DSP 3 OEI DVD RRP Commrcl",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro Refurbisher",
    "Start Effective Date": "08/04/2014",
    "End Effective Date": "11/01/2016",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "10/31/2016",
    Language: "French",
    "Add Date": "08/01/2014"
  },
  {
    value: "QLF-00579",
    Description:
      "Win Pro Refurbisher 10 32-bit English 3pk DSP 3 OEI DVD RRP Commrcl",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro Refurbisher",
    "Start Effective Date": "09/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "09/01/2016"
  },
  {
    value: "QLF-00580",
    Description:
      "Win Pro Refurbisher 10 32-bit French 3pk DSP 3 OEI DVD RRP Commrcl",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro Refurbisher",
    "Start Effective Date": "09/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "09/01/2016"
  },
  {
    value: "QLF-00585",
    Description:
      "Win Pro Refurbisher 10 64-bit English 3pk DSP 3 OEI DVD RRP Commrcl",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro Refurbisher",
    "Start Effective Date": "09/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "09/01/2016"
  },
  {
    value: "QLF-00586",
    Description:
      "Win Pro Refurbisher 10 64-bit French 3pk DSP 3 OEI DVD RRP Commrcl",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Pro Refurbisher",
    "Start Effective Date": "09/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "09/01/2016"
  },
  {
    value: "QQF-00050",
    Description:
      "Win Refurbisher 8.1 32-bit English 3pk DSP 3 OEI DVD RRP Commrcl",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Refurbisher",
    "Start Effective Date": "08/04/2014",
    "End Effective Date": "11/01/2016",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "10/31/2016",
    Language: "English",
    "Add Date": "08/01/2014"
  },
  {
    value: "QQF-00053",
    Description:
      "Win Refurbisher 8.1 32-bit French 3pk DSP 3 OEI DVD RRP Commrcl",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Refurbisher",
    "Start Effective Date": "08/04/2014",
    "End Effective Date": "11/01/2016",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "10/31/2016",
    Language: "French",
    "Add Date": "08/01/2014"
  },
  {
    value: "QQF-00076",
    Description:
      "Win Refurbisher 8.1 64-bit English 3pk DSP 3 OEI DVD RRP Commrcl",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Refurbisher",
    "Start Effective Date": "08/04/2014",
    "End Effective Date": "11/01/2016",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "10/31/2016",
    Language: "English",
    "Add Date": "08/01/2014"
  },
  {
    value: "QQF-00079",
    Description:
      "Win Refurbisher 8.1 64-bit French 3pk DSP 3 OEI DVD RRP Commrcl",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Refurbisher",
    "Start Effective Date": "08/04/2014",
    "End Effective Date": "11/01/2016",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "10/31/2016",
    Language: "French",
    "Add Date": "08/01/2014"
  },
  {
    value: "R18-03665",
    Description: "Windows Server CAL 2012 English 1pk DSP OEI 1 Clt Device CAL",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server CAL",
    "Start Effective Date": "09/01/2012",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "09/01/2012"
  },
  {
    value: "R18-03666",
    Description: "Windows Server CAL 2012 French 1pk DSP OEI 1 Clt Device CAL",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server CAL",
    "Start Effective Date": "09/01/2012",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "09/01/2012"
  },
  {
    value: "R18-03683",
    Description: "Windows Server CAL 2012 English 1pk DSP OEI 5 Clt Device CAL",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server CAL",
    "Start Effective Date": "09/01/2012",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "09/01/2012"
  },
  {
    value: "R18-03684",
    Description: "Windows Server CAL 2012 French 1pk DSP OEI 5 Clt Device CAL",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server CAL",
    "Start Effective Date": "09/01/2012",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "09/01/2012"
  },
  {
    value: "R18-03737",
    Description: "Windows Server CAL 2012 English 1pk DSP OEI 1 Clt User CAL",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server CAL",
    "Start Effective Date": "08/01/2015",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "09/01/2012"
  },
  {
    value: "R18-03738",
    Description: "Windows Server CAL 2012 French 1pk DSP OEI 1 Clt User CAL",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server CAL",
    "Start Effective Date": "08/01/2015",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "09/01/2012"
  },
  {
    value: "R18-03755",
    Description: "Windows Server CAL 2012 English 1pk DSP OEI 5 Clt User CAL",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server CAL",
    "Start Effective Date": "08/01/2015",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "09/01/2012"
  },
  {
    value: "R18-03756",
    Description: "Windows Server CAL 2012 French 1pk DSP OEI 5 Clt User CAL",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server CAL",
    "Start Effective Date": "08/01/2015",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "09/01/2012"
  },
  {
    value: "R18-05187",
    Description: "Windows Server CAL 2016 English 1pk DSP OEI 1 Clt Device CAL",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server CAL",
    "Start Effective Date": "10/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "10/01/2016"
  },
  {
    value: "R18-05188",
    Description: "Windows Server CAL 2016 French 1pk DSP OEI 1 Clt Device CAL",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server CAL",
    "Start Effective Date": "10/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "10/01/2016"
  },
  {
    value: "R18-05206",
    Description: "Windows Server CAL 2016 English 1pk DSP OEI 5 Clt Device CAL",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server CAL",
    "Start Effective Date": "10/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "10/01/2016"
  },
  {
    value: "R18-05207",
    Description: "Windows Server CAL 2016 French 1pk DSP OEI 5 Clt Device CAL",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server CAL",
    "Start Effective Date": "10/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "10/01/2016"
  },
  {
    value: "R18-05225",
    Description: "Windows Server CAL 2016 English 1pk DSP OEI 1 Clt User CAL",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server CAL",
    "Start Effective Date": "10/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "10/01/2016"
  },
  {
    value: "R18-05226",
    Description: "Windows Server CAL 2016 French 1pk DSP OEI 1 Clt User CAL",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server CAL",
    "Start Effective Date": "10/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "10/01/2016"
  },
  {
    value: "R18-05244",
    Description: "Windows Server CAL 2016 English 1pk DSP OEI 5 Clt User CAL",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server CAL",
    "Start Effective Date": "10/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "10/01/2016"
  },
  {
    value: "R18-05245",
    Description: "Windows Server CAL 2016 French 1pk DSP OEI 5 Clt User CAL",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Windows Server CAL",
    "Start Effective Date": "10/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Future",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "10/01/2016"
  },
  {
    value: "WN7-00615",
    Description: "Win 8.1 x64 English 1pk DSP OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win",
    "Start Effective Date": "09/01/2013",
    "End Effective Date": "11/01/2016",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "10/31/2016",
    Language: "English",
    "Add Date": "09/01/2013"
  },
  {
    value: "WN7-00618",
    Description: "Win 8.1 x64 French 1pk DSP OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win",
    "Start Effective Date": "09/01/2013",
    "End Effective Date": "11/01/2016",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "10/31/2016",
    Language: "French",
    "Add Date": "09/01/2013"
  },
  {
    value: "WN7-00650",
    Description: "Win 8.1 x32 French 1pk DSP OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win",
    "Start Effective Date": "09/01/2013",
    "End Effective Date": "11/01/2016",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "10/31/2016",
    Language: "French",
    "Add Date": "09/01/2013"
  },
  {
    value: "WN7-00659",
    Description: "Win 8.1 x32 English 1pk DSP OEI DVD",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win",
    "Start Effective Date": "09/01/2013",
    "End Effective Date": "11/01/2016",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "10/31/2016",
    Language: "English",
    "Add Date": "09/01/2013"
  },
  {
    value: "WN7-01144",
    Description:
      "Win 8.1 32-bit/x64 English 1pk DSP OEI Not to China Medialess",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win",
    "Start Effective Date": "12/01/2013",
    "End Effective Date": "11/01/2016",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "10/31/2016",
    Language: "English",
    "Add Date": "12/01/2013"
  },
  {
    value: "WN7-01145",
    Description: "Win 8.1 32-bit/x64 French 1pk DSP OEI Not to China Medialess",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win",
    "Start Effective Date": "12/01/2013",
    "End Effective Date": "11/01/2016",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "10/31/2016",
    Language: "French",
    "Add Date": "12/01/2013"
  },
  {
    value: "WV2-00005",
    Description:
      "Win Home Refurbisher 10 32-bit English 3pk DSP 3 OEI DVD RRP Commrcl",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Home Refurbisher",
    "Start Effective Date": "09/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "09/01/2016"
  },
  {
    value: "WV2-00006",
    Description:
      "Win Home Refurbisher 10 32-bit French 3pk DSP 3 OEI DVD RRP Commrcl",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Home Refurbisher",
    "Start Effective Date": "09/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "09/01/2016"
  },
  {
    value: "WV2-00011",
    Description:
      "Win Home Refurbisher 10 64-bit English 3pk DSP 3 OEI DVD RRP Commrcl",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Home Refurbisher",
    "Start Effective Date": "09/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "English",
    "Add Date": "09/01/2016"
  },
  {
    value: "WV2-00012",
    Description:
      "Win Home Refurbisher 10 64-bit French 3pk DSP 3 OEI DVD RRP Commrcl",
    "Item Legal Name": "",
    "License Type": "Delivery Service Partner",
    "Program Offering": "OD NON NON EA NON NON",
    label: "Win Home Refurbisher",
    "Start Effective Date": "09/01/2016",
    "End Effective Date": "",
    "Mfg System Product Status": "Active",
    "Unit Count": "Non-specific",
    "Promotion Code Name": "",
    "Date Discontinued": "",
    Language: "French",
    "Add Date": "09/01/2016"
  }
];
